// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bwuanqwpgtnanlucbxrs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ3dWFucXdwZ3RuYW5sdWNieHJzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDA3MzU2NTcsImV4cCI6MjA1NjMxMTY1N30.eSo5nd6olvrTAuHKBSrnInnZO5IkoOmPVVOF9Tqnw14";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);